info:
  component: Order Service

server:
  port: ${PORT:${vcap.application.port:8082}}

logging:
  file: ${user.home}/Downloads/log/order-service.log

entitymanager:
  packagesToScan: com.project

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_USER_URL:${JDBC_URL:jdbc:postgresql://localhost:5432/micro?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&characterEncoding=UTF-8}}
    username: ${JDBC_USER_USER:${JDBC_USER:postgres}}
    password: ${JDBC_USER_PASS:${JDBC_PASS:postgres}}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

---

security:
  basic:
    enabled: true
  user:
    name: ${EUREKA_USERNAME:user}
    password: ${EUREKA_PASSWORD:12345}